### ISSUE TITLE
Can't find VerizonVideoPartnerSDK

### ISSUE THREAD

**Issue by wanght** [VerizonAdPlatforms/VerizonVideoPartnerSDK-iOS#125]
When I search VerizonVideoPartnerSDK by using: 
pod search VerizonVideoPartnerSDK
the result is:
[!] Unable to find a pod with name, author, summary, or description matching `VerizonVideoPartnerSDK`
How can use this SDK? 
My cocopods version is: 1.5.3, and have run 'pod repo update' many times ...
Also, tried 1.6.2, and gem sources are:
http://gems.github.com/
https://rubygems.org/

**Comment by davidpaulhunt** [comment]
I'm having the same issue `[!] Unable to find a specification for 'VerizonVideoPartnerSDK'`.

Pointing directly to the repo almost works... except then it can't find the dependent pods.

**Comment by davidpaulhunt** [comment]
Okay, so I was able to install by adding the pod as a source. Now at the top of my podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/VerizonAdPlatforms/VerizonVideoPartnerSDK-releases-iOS'
```
