### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020

### ISSUE THREAD

**Issue by lee-joseph** [VerizonAdPlatforms/VerizonVideoPartnerSDK-iOS#131]
Hello. We are using MoPub to mediate Verizon-Ads-StandardEdition at our company. Are you still using UIWebView within your SDK? And if not starting from which version have you deprecated UIWebView usage? We're currently on Verizon-Ads-StandardEdition version 1.3.1. Thanks.

**Comment by mewpre** [comment]
After updating OMSDK in the latest release (1.5.3), we are no longer using UIWebView in the SDK.
